### ISSUE TITLE
WPA Password found but hashlist still says not cracked.

### ISSUE THREAD

**Issue by winxp5421** [curlyboi/hashtopus#10]
When cracking wpa and the password is found. hashtopus stops all tasks for the hash list and the last chunk says its cracked but the clear text password is not shown in the hash list page if you import the clear text password as a Pre-cracked hash in the format SSID:password it works as intended.

**Comment by curlyboi** [comment]
could you provide me with the HCCAP file and the known plaintext?

**Comment by winxp5421** [comment]
I have not been able to get hashtopus to "automatically" provide the clear text on any wpa file i have always needed to re-run the last task manually with hashcat in order to get the plain text pass.
This should provide you with everything.
https://hashcat.reifr.net/owncloud/index.php/s/8gRoTt2WRRWLG7d

Thanks for your hard work Curlyboi!

**Comment by curlyboi** [comment]
Ok, I analyzed the results and was able to replicate the issue. The problem is in hashcat output itself. It used to output just "ESSID-PLAINTEXT" (where - is separator) but now it outputs "ESSID:hexvalue1:hexvalue2-PLAINTEXT" (it uses : regardless of what separator you specify). I don't know what the hexvalues are, nor do I know why it ignores the separator in them. Hashtopus interprets this as if the ESSID was "ESSID:hexvalue1:hexvalue2" and because this doesn't exist in the database, the plaintext doesn't get updated. I will contact hashcat team and have this explained to me, then I will submit new version of hashtopus with the fix. Stay tuned.

**Comment by winxp5421** [comment]
Awesome thank you!

**Comment by curlyboi** [comment]
Quick-fixed to make it work. In a few days I plan to fix it properly so you can have multiple WPA networks with the same ESSID (differentiate by MAC addresses instead)

**Comment by timonline** [comment]
@curlyboi I am facing a similar issue, hashtopus says it's cracked but never shows the password. Please find the images below:

I am running hashtopus 0.9.7

![cracked but no password](https://cloud.githubusercontent.com/assets/500310/9701797/bd0b4114-543d-11e5-9e85-83043fe7b5d0.jpg)

Any assistance will be GREAT!
