### ISSUE TITLE
wpa/wpa2 with dict+rules = serious speed drop

### ISSUE THREAD

**Issue by JuggyMcNutty** [curlyboi/hashtopus#7]
Hello thanks for the great program little buggy but very awesome i have found a bug that affects all platforms (windows/ubuntu) while using hashtopus on wpa hccap file with wordlist attack, speed is normal but as soon as a rule file is added speed drops by 80%ish... to test if it was a oclhashcat problem  i preformed both attacks with just hashcat and found everything to be normal. also while i run the rule based attack with wordlist hashtopus no longer gives out correct chunk sizes (<example> i give task 300s chunk size and it takes roughly 25 mins or more to complete that chunk)

If you need anymore info or testing done please let me know!

**Comment by curlyboi** [comment]
Please try to run hashtopus.exe debug to see what exact command is the hashtopus executing with hashcat, then post the differences here. I suspect that the problem is when the tast benchmarks, maybe it takes extra time for some kind of loading data into memory and therefore the benchmark is invalid. Hashtopus then bases its chunk calculations on this bad value.

**Comment by JuggyMcNutty** [comment]
After i rebooted my server and all agents i have been unable to reproduce the results i will continue to attempt to recreate the results and will post back when i can.

**Comment by curlyboi** [comment]
closing due to long inactivity
